import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'


export default function Home() {
  return (
    <>
      <Head>
        <title>Multi-step-form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.form}>
          <div className={styles.form_choice}>
            <div className={styles.choice}>
              <span className={styles.circle}>
                1
              </span>
              <div>
                <p>
                  STEP 1
                </p>
                <p>
                  YOUR INFO
                </p>
              </div>
            </div>
            <div className={styles.choice} >
              <span className={styles.circle}>
                2
              </span>
              <div>
                <p>
                  STEP 2
                </p>
                <p>
                  SELECT PLAN
                </p>
              </div>
            </div>
            <div className={styles.choice}>
              <span className={styles.circle}>
                3
              </span>
              <div>
                <p>
                  STEP 3
                </p>
                <p>
                  ADD-ONS
                </p>
              </div>
            </div>
            <div className={styles.choice}>
              <span className={styles.circle}>
                4
              </span>
              <div>
                <p>
                  STEP 4
                </p>
                <p>
                  SUMMARY
                </p>
              </div>
            </div>
          </div>
          <div className={styles.form_documents}>

          </div>
        </div>
      </main>
    </>
  )
}
